// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8CW5tqalTa4Z4Ai_tuMN5YIeeozov3eE',
    appId: '1:862935678742:web:d717b632b404fee9431a37',
    messagingSenderId: '862935678742',
    projectId: 'bahiapp-76870',
    authDomain: 'bahiapp-76870.firebaseapp.com',
    storageBucket: 'bahiapp-76870.appspot.com',
    measurementId: 'G-CSRBKTPP34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiMJLr89pTHJF-VyOOoV-opIAZMf0PjV8',
    appId: '1:862935678742:android:1473b039d0b24b87431a37',
    messagingSenderId: '862935678742',
    projectId: 'bahiapp-76870',
    storageBucket: 'bahiapp-76870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFZmYRhmfw9KNxTTvKfEDAGKgh8wRl0yY',
    appId: '1:862935678742:ios:f2dcbf45ee2079d8431a37',
    messagingSenderId: '862935678742',
    projectId: 'bahiapp-76870',
    storageBucket: 'bahiapp-76870.appspot.com',
    iosBundleId: 'com.example.bahriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFZmYRhmfw9KNxTTvKfEDAGKgh8wRl0yY',
    appId: '1:862935678742:ios:f2dcbf45ee2079d8431a37',
    messagingSenderId: '862935678742',
    projectId: 'bahiapp-76870',
    storageBucket: 'bahiapp-76870.appspot.com',
    iosBundleId: 'com.example.bahriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8CW5tqalTa4Z4Ai_tuMN5YIeeozov3eE',
    appId: '1:862935678742:web:86561c7a01100194431a37',
    messagingSenderId: '862935678742',
    projectId: 'bahiapp-76870',
    authDomain: 'bahiapp-76870.firebaseapp.com',
    storageBucket: 'bahiapp-76870.appspot.com',
    measurementId: 'G-SPMSN96QN2',
  );
}
